/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    requests: Request;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'terms-conditions': TermsCondition;
  };
  globalsSelect: {
    'terms-conditions': TermsConditionsSelect<false> | TermsConditionsSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Gerencie os usuários que poderão acessar o painel administrativo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Selecione as funções do usuário
   */
  roles: ('ADMIN' | 'CUSTOMER')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Clientes cadastrados na plataforma.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  cpf: string;
  phone: string;
  cro: {
    number: string;
    state:
      | 'AC'
      | 'AL'
      | 'AP'
      | 'AM'
      | 'BA'
      | 'CE'
      | 'DF'
      | 'ES'
      | 'GO'
      | 'MA'
      | 'MT'
      | 'MS'
      | 'MG'
      | 'PA'
      | 'PB'
      | 'PR'
      | 'PE'
      | 'PI'
      | 'RJ'
      | 'RN'
      | 'RS'
      | 'RO'
      | 'RR'
      | 'SC'
      | 'SP'
      | 'SE'
      | 'TO';
  };
  address: {
    postalCode: string;
    street: string;
    number: string;
    complement?: string | null;
    neighborhood: string;
    city: string;
    state:
      | 'AC'
      | 'AL'
      | 'AP'
      | 'AM'
      | 'BA'
      | 'CE'
      | 'DF'
      | 'ES'
      | 'GO'
      | 'MA'
      | 'MT'
      | 'MS'
      | 'MG'
      | 'PA'
      | 'PB'
      | 'PR'
      | 'PE'
      | 'PI'
      | 'RJ'
      | 'RN'
      | 'RS'
      | 'RO'
      | 'RR'
      | 'SC'
      | 'SP'
      | 'SE'
      | 'TO';
  };
  /**
   * Preferências clínicas globais aplicadas aos tratamentos do cliente.
   */
  clinicalPreferences?: {
    passiveAligners?: ('sim_adicione' | 'nao_mas_crie' | 'nenhuma') | null;
    delayIPRStage?: ('nao_atrase' | 'estagio_1' | 'estagio_2' | 'estagio_3' | 'estagio_4' | 'estagio_5') | null;
    /**
     * Especifique o valor máximo de IPR permitido (ex: 0.5mm)
     */
    maxIPR?: string | null;
    delayAttachmentStage?: ('nao_atrase' | 'estagio_1' | 'estagio_2' | 'estagio_3' | 'estagio_4' | 'estagio_5') | null;
    incisalLeveling?: ('nivelar_borda' | 'nivelar_laterais_centrais' | 'laterais_05mm' | 'margem_gengival') | null;
    elasticChain?: ('nao' | 'sim_3_3' | 'sim_6_6') | null;
    distalizationOptions?: ('sequencial_50' | '2by2') | null;
    elasticPositions?:
      | (
          | '18'
          | '17'
          | '16'
          | '15'
          | '14'
          | '13'
          | '12'
          | '11'
          | '21'
          | '22'
          | '23'
          | '24'
          | '25'
          | '26'
          | '27'
          | '28'
          | '48'
          | '47'
          | '46'
          | '45'
          | '44'
          | '43'
          | '42'
          | '41'
          | '31'
          | '32'
          | '33'
          | '34'
          | '35'
          | '36'
          | '37'
          | '38'
        )[]
      | null;
    specialInstructions?: string | null;
  };
  /**
   * Marque esta opção para definir se o cliente está ativo ou inativo.
   */
  isActive?: boolean | null;
  requests?: (number | Request)[] | null;
  isRegisterComplete?: boolean | null;
  roles?: 'CUSTOMER'[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Formulários de prescrição para novos tratamentos com alinhadores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  publicId?: string | null;
  titleForList?: string | null;
  /**
   * ID sequencial único gerado automaticamente quando a solicitação é finalizada.
   */
  orderId?: number | null;
  /**
   * Data em que a solicitação foi marcada como concluída.
   */
  completionDate?: string | null;
  customer: number | Customer;
  patient: string;
  /**
   * Qualquer outra informação relevante para este caso que não se encaixa nos campos acima.
   */
  additionalInfo?: string | null;
  documents?:
    | {
        documentName: string;
        documentFile: number | Media;
        id?: string | null;
      }[]
    | null;
  archToTreat: 'none' | 'both' | 'upper' | 'lower';
  /**
   * Selecione algum dente que NÃO deseje movimentar na arcada SUPERIOR (implante, anquilose, prótese, etc).
   */
  upperJawMovementRestriction?:
    | ('11' | '12' | '13' | '14' | '15' | '16' | '17' | '18' | '21' | '22' | '23' | '24' | '25' | '26' | '27')[]
    | null;
  /**
   * Selecione algum dente que NÃO deseje movimentar na arcada INFERIOR (implante, anquilose, prótese, etc).
   */
  lowerJawMovementRestriction?:
    | ('31' | '32' | '33' | '34' | '35' | '36' | '37' | '38' | '41' | '42' | '43' | '44' | '45' | '46' | '47')[]
    | null;
  apRelationUpper?: ('improve_canine' | 'improve_canine_and_molar' | 'improve_molar' | 'none') | null;
  apRelationLower?: ('improve_canine' | 'improve_canine_and_molar' | 'improve_molar' | 'none') | null;
  /**
   * Detalhes sobre a distalização "2 by 2" ou em bloco de no máximo 2mm.
   */
  distalizationInstructions?: string | null;
  elasticCutouts?: {
    canineElastic?: ('right' | 'left' | 'both' | 'none') | null;
    canineButton?: ('right' | 'left' | 'both' | 'none') | null;
    molarElastic?: ('right' | 'left' | 'both' | 'none') | null;
    molarButton?: ('right' | 'left' | 'both' | 'none') | null;
  };
  elasticCutoutInstructions?: string | null;
  useAttachments: 'yes' | 'no';
  upperJawNoAttachments?:
    | ('11' | '12' | '13' | '14' | '15' | '16' | '17' | '18' | '21' | '22' | '23' | '24' | '25' | '26' | '27')[]
    | null;
  lowerJawNoAttachments?:
    | ('31' | '32' | '33' | '34' | '35' | '36' | '37' | '38' | '41' | '42' | '43' | '44' | '45' | '46' | '47')[]
    | null;
  /**
   * Limite padrão de 0,5mm entre as faces.
   */
  performIPR: 'yes' | 'no' | 'detail_below';
  /**
   * Caso deseje, detalhe a região exata de onde fazer (IPR). Por exemplo: fazer IPR de 0,3mm entre os dentes 44 e 45.
   */
  iprDetails?: string | null;
  /**
   * No caso de presença de DIASTEMAS não visualizados no escaneamento, por favor descrever exatamente a região a ser movimentada. Por exemplo: fechar diastema de 0,2mm entre os dentes 16 e 17.
   */
  diastemaInstructions?: string | null;
  generalInstructions?: string | null;
  /**
   * Este é o status atual do tratamento. Este campo pode ser alterado a qualquer momento.
   */
  status: 'documentation_check' | 'in_progress' | 'completed';
  /**
   * Link externo para o planejamento virtual ou acompanhamento do caso.
   */
  trackingLink?: string | null;
  payment: {
    status: 'not_paid' | 'paid';
    /**
     * Insira o link de pagamento via Pix.
     */
    pixUrl?: string | null;
    /**
     * Insira o link de pagamento via Cartão de Crédito.
     */
    cardUrl?: string | null;
  };
  tracking: {
    status: 'not_sent' | 'preparing' | 'sent' | 'delivered';
    carrier?: string | null;
    /**
     * Código de rastreio dos Correios ou transportadora.
     */
    trackingCode?: string | null;
    /**
     * Link direto para a página de rastreio.
     */
    trackingUrl?: string | null;
    /**
     * A data em que o pedido foi efetivamente enviado.
     */
    sentDate?: string | null;
    /**
     * A data estimada para a entrega do pedido.
     */
    estimatedArrival?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gerencie os arquivos de mídia do site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  cpf?: T;
  phone?: T;
  cro?:
    | T
    | {
        number?: T;
        state?: T;
      };
  address?:
    | T
    | {
        postalCode?: T;
        street?: T;
        number?: T;
        complement?: T;
        neighborhood?: T;
        city?: T;
        state?: T;
      };
  clinicalPreferences?:
    | T
    | {
        passiveAligners?: T;
        delayIPRStage?: T;
        maxIPR?: T;
        delayAttachmentStage?: T;
        incisalLeveling?: T;
        elasticChain?: T;
        distalizationOptions?: T;
        elasticPositions?: T;
        specialInstructions?: T;
      };
  isActive?: T;
  requests?: T;
  isRegisterComplete?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  publicId?: T;
  titleForList?: T;
  orderId?: T;
  completionDate?: T;
  customer?: T;
  patient?: T;
  additionalInfo?: T;
  documents?:
    | T
    | {
        documentName?: T;
        documentFile?: T;
        id?: T;
      };
  archToTreat?: T;
  upperJawMovementRestriction?: T;
  lowerJawMovementRestriction?: T;
  apRelationUpper?: T;
  apRelationLower?: T;
  distalizationInstructions?: T;
  elasticCutouts?:
    | T
    | {
        canineElastic?: T;
        canineButton?: T;
        molarElastic?: T;
        molarButton?: T;
      };
  elasticCutoutInstructions?: T;
  useAttachments?: T;
  upperJawNoAttachments?: T;
  lowerJawNoAttachments?: T;
  performIPR?: T;
  iprDetails?: T;
  diastemaInstructions?: T;
  generalInstructions?: T;
  status?: T;
  trackingLink?: T;
  payment?:
    | T
    | {
        status?: T;
        pixUrl?: T;
        cardUrl?: T;
      };
  tracking?:
    | T
    | {
        status?: T;
        carrier?: T;
        trackingCode?: T;
        trackingUrl?: T;
        sentDate?: T;
        estimatedArrival?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Termo de prestação de serviços
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-conditions".
 */
export interface TermsCondition {
  id: number;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-conditions_select".
 */
export interface TermsConditionsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}